spring.application.name=redis
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
# mật khẩu truy cập
spring.data.redis.password=123
# thời gian chờ kết nối
spring.data.redis.timeout=2000